apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-k8s-app
  namespace: argocd
spec:
  destination:
    namespace: app-namespace
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/balaajimuthukumar/agrocdrepo.git
    targetRevision: main
    path: my-k8s-repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
